name: Frontend CI

on: 
  push:
    branches:
      - main

jobs:
  checks: 
    name: Lint, Typecheck and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js 
        uses: actions/setup-node/@v4
        with:
          - node-version: 22
            cache: npm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run project checks
        run: pnpm check
